[package]
name = "prometheus-manager"
version = "0.0.8" # https://crates.io/crates/prometheus-manager
edition = "2021"
rust-version = "1.63"
publish = true
description = "Rust random manager"
repository = "https://github.com/gyuho/prometheus-manager"
readme = "README.md"
license = "Apache-2.0"

[dependencies]
chrono = "0.4.22"
human-readable = "0.0.1"
lazy_static = "1.4.0"
log = "0.4.17"
regex = "1.6.0"
serde = { version = "1.0.144", features = ["derive"] }
serde_yaml = "0.9.10" # https://github.com/dtolnay/serde-yaml/releases

[dev-dependencies]
env_logger = "0.9.0"
rust-embed = "6.4.0"
